

CREATE TABLE Department (
    DeptID INT PRIMARY KEY,
	DeptName VARCHAR(50)
); 

INSERT INTO Department VALUES 
(10, 'CSE'),
(20, 'ECE'),
(30, 'ME'); 

CREATE TABLE student (
    Roll INT PRIMARY KEY,
	Name VARCHAR(50),
	DeptID INT,
	Marks INT, 
	FOREIGN KEY (DeptID) REFERENCES Department(DeptID)
); 


INSERT INTO student VALUES 
(1, 'Asha', 10, 85), 
(2, 'Rahul', 20, 78),
(3, 'Neha', 10, 92),
(4, 'Amit', 30, 60),
(5, 'Sneha', 20,80);  

CREATE TABLE Course (
    CourseID INT PRIMARY KEY,
	CourseName VARCHAR(50), 
	DeptID INT, 
	FOREIGN KEY (DeptID) REFERENCES Department(DeptID)
); 

INSERT INTO Course VALUES 
(101, 'DBMS', 10), 
(102, 'Networks', 20),
(103, 'Physics', 30); 

SELECT * FROM department;
SELECT * FROM student;
SELECT * FROM Course; 

SELECT NAME, MARKS FROM STUDENT;
SELECT  MARKS FROM STUDENT; 

SELECT * FROM STUDENT 
WHERE MARKS >80; 

SELECT * FROM STUDENT 
WHERE MARKS >85 AND DEPTID = 10; 

SELECT * FROM STUDENT 
ORDER BY MARKS DESC; 

SELECT DISTINCT DEPTID FROM STUDENT; 

SELECT AVG(MARKS) FROM STUDENT; 
SELECT MAX(MARKS) FROM STUDENT;
SELECT MIN(MARKS) FROM STUDENT;
SELECT COUNT(*) FROM STUDENT; 

SELECT DEPTID, AVG(MARKS) FROM STUDENT GROUP BY DEPTID; 
SELECT DEPTID, AVG(MARKS) FROM STUDENT GROUP BY DEPTID; 

SELECT S.NAME , D.DEPTNAME FROM STUDENT S INNER JOIN DEPARTMENT D ON S.DEPTID = D.DEPTID;